config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :products
  resources :events
  resource :cart, only: [:show]
  resource :account, only: [:show]


  resources :users, only: [:index]


  resources :orders do
  resources :order_items
  end
  resources :order_items
  resources :addresses do
    resources :charges
  end


  root :to => 'welcome#index'

end

app/models/event.rb
class Event < ApplicationRecord

  has_attached_file :images, styles: { medium: "300x300>", thumb: "100x100>", large: "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :images, content_type: /\Aimage\/.*\z/

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :location, :date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for [@event], url: events_path, html: { multipart: true } do |form| %>

  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control", id: :event_title %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "form-control", id: :event_content %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, :class => "form-control", id: :event_location %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.text_field :date, :class => "form-control", id: :event_date %>
  </div>

  <div class="form-group">
    <%= form.file_field :images %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/events/_form2.html.erb
<%= form_for [@event], url: event_path, html: { multipart: true } do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control", id: :event_title %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "form-control", id: :event_content %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, :class => "form-control", id: :event_location %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.text_field :date, :class => "form-control", id: :event_date %>
  </div>

  <div class="form-group">
    <%= form.file_field :images %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="events">
  <div class="container">
    <br><br>

    <h1>Editing Event</h1>

    <%= render 'form2', event: @event %>

    <%= link_to 'Show', @event %> |
    <%= link_to 'Back', events_path %>
  </div>
</div>

app/views/events/index.html.erb
  <div class="events">
    <div class="container">

    <p id="notice"><%= notice %></p>
    <br>
    <h1 style="text-align:center;">Events</h1>
    
  <ul>
    <% @events.each do |event| %>
          <%= image_tag event.images.url(:large) %>
      <h1><%= event.title %></h1>
      <h3> What?</h3>
      <%= event.content %>
      <h3>Where?</h3>
      <%= event.location %>
      <h3>When?</h3>
      <%= event.date %>
      <br>
      <br>
      <hr>
      <% if is_admin? %>
      <div class="row">
        <div class="col-md-4">
          <%= link_to 'Event Page', event, :class => "btn btn-primary btn-lg" %>
        </div>
        <div class="col-md-4">
          <%= link_to 'Edit', edit_event_path(event), :class => "btn btn-primary btn-lg" %>
        </div>
        <div class="col-md-4">
          <%= link_to 'Destroy', event,:class => "btn btn-primary btn-lg", method: :delete, data: { confirm: 'Are you sure?' } %>
          <hr>
          <br>
        </div>
        <hr>
        <% end %>
        <% end %>
        <% if is_admin? %>
          <%= link_to 'New Event', new_event_path, :class => "btn btn-primary btn-lg" %>
        <% end %>
        </div>
      </ul>

    <br>
    <br>
    <br>

  </div>
</div>

app/views/events/new.html.erb
<div class="events">
  <br>
  <br>
  <br>

  <h1 style="text-align:center;">Add a New Upcoming Event</h1>
  <div class="container">
    <h1>New Event</h1>
    <%= render 'form', event: @event %>
    <br>
    <%= link_to 'Back', events_path, :class => "btn btn-primary" %>
  </div>
  <br>
</div>

app/views/events/show.html.erb
<div class="events">
  <div class="container">
      <br>
          <div class="title-bar">
            <h1><%= @event.title %></h1>
          </div>
      <div class="container">

        <p id="notice"><%= notice %></p>

          <%= image_tag @event.images.url(:large), :style => 'display:inline-block;' %>
          <h3><%= @event.title %></h3>

          <h3>What?</h3>
          <%= @event.content %>


          <h3>Where?</h3>
          <%= @event.location %>


          <h3>When?</h3>
          <%= @event.date %>
    <br><br>
      <% if is_admin? %>
        <%= link_to 'Edit', edit_event_path(@event), :class => "btn btn-primary btn-lg", :style => "margin:10px;" %>
      <% end %>
        <%= link_to 'Back', events_path, :class => "btn btn-primary btn-lg" %>
        </div>
    <br><br>
  </div>
</div>