config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :products
  resources :events
  resource :cart, only: [:show]
  resource :account, only: [:show]


  resources :users, only: [:index]


  resources :orders do
  resources :order_items
  end
  resources :order_items
  resources :addresses do
    resources :charges
  end


  root :to => 'welcome#index'

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to  :user

  has_many :orders
  has_many :addresses
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :account
  has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_attached_file :images, styles: { medium: "300x300>", thumb: "100x100>", large: "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :images, content_type: /\Aimage\/.*\z/

end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :product

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", large: "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  belongs_to :account
  has_one :address

  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :account

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
    @account = Account.find_by(user_id: current_user.id)
    @account_history = @account.orders.where(status: "Paid")

  end

end

# @account.addresses.where(@account_history.find(29).address_id)

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = Address.where(account_id: current_user.account.id).all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end


  def create
    @address = Address.new(address_params)
    @address.account_id = (Account.find_by(user_id: current_user.id)).id
    respond_to do |format|
      if @address.save
        format.html { redirect_to addresses_path, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :zip)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = current_order.total_price * 100
    @address = Address.find(params[:address_id])
  end

  def create
    # Amount in cents
    @amount = (current_order.total_price * 100).to_i
    @address = Address.find(params[:address_id])

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken],
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    current_order.update({:status => "Paid",:address_id => @address.id})
    current_user.account.update({:address_id => @address.id})
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def charges_params
    params.require(:charges).permit(:address)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :location, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
    @number = rand(1..15)
    @events = Event.all
    @remoteip = request.remote_ip

  end


private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :content, :location, :date, :images)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@address], url: addresses_path, html: {multipart: true } do |form |%>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :address_street, :placeholder => 'Street' %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :address_city, :placeholder => 'City' %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :address_state, :placeholder => 'State' %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip, id: :address_zip, :placeholder => 'Zip Code' %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :address_phone, :placeholder => 'Phone Number' %>
  </div>

  <%= form.hidden_field :account_id, value: @account %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<div class="events">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <h1>Addresses on File</h1>



        <% @addresses.each do |address| %>
        <ul>
            <%= address.street %>
            <%= address.city %>
            <%= address.state %>
            <%= address.zip %>

            <%= link_to 'Ship to this Address', new_address_charge_path(address) %>
            <br>

            <%= link_to 'Edit', edit_address_path(address) %>
            <%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %>
        </ul>
        <% end %>

    <br>
    <br>

    <%= link_to 'New Address', new_address_path %>
    <div class="spacer" style="height:500px;"></div>
  </div>
</div>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<div class="events">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Street:</strong>
      <%= @address.street %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @address.city %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @address.state %>
    </p>

    <p>
      <strong>Zip:</strong>
      <%= @address.zip %>
    </p>

    <%= link_to 'Edit', edit_address_path(@address) %> |
    <%= link_to 'Back', addresses_path %>

  </div>
</div>