config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :products
  resources :events
  resource :cart, only: [:show]
  resource :account, only: [:show]


  resources :users, only: [:index]


  resources :orders do
  resources :order_items
  end
  resources :order_items
  resources :addresses do
    resources :charges
  end


  root :to => 'welcome#index'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :order_items

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_action :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end


  def index
    if current_order.status == "Paid"
      session[:order_id] = nil
    end
    @products = Product.all
    @order_item = current_order.order_items.new

  end

  def show
    @order = current_order
    @order_items = current_order.order_items.new
    @product = Product.find(params[:id])
      respond_to do |format|
      format.html { redirect_to products_path}
      format.js
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end


  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        if params[:product][:image]
          params[:product][:image].each { |image|
            @product.images.create(image: image)
          }
        end
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
    <%= form_for [@product], url: products_path, html: { multipart: true } do |form| %>

      <div class="form-group">
        <%= "When given the choice, I prefer to be given a task list to run with." %>
        <%= form.text_field :title, :class => "form-control", id: :product_title %>
      </div>

      <%= radio_button_tag(:remoteOneValue, "child") %>
      <%= label_tag(:age_child, "I am younger than 21") %>
      <%= radio_button_tag(:age, "adult") %>
      <%= label_tag(:age_adult, "I'm over 21") %>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, :class => "form-control", id: :product_description %>
      </div>

      <div class="form-group">
        <%= form.label :price %>
        <%= form.number_field :price, value: number_to_currency(form.object.price.to_f, delimiter: '', unit: ''), step: :any, :class => "form-control", id: :product_price %>
      </div>


      <div class="form-group">
        <%= form.label :category %>
        <br>
        <%= form.select :category, options_for_select([['Select One', ''], 'independant', 'graphic novel','merchandise']), :class => "form-control"%>
      </div>

      <div class="control-group">
        <div class="controls">
          <%= form.label :image %>
          <%= form.file_field :image, type: :file, multiple: true %>
        </div>
      </div>
      <br>

      <div class="actions">
        <%= form.submit :class => "btn btn-primary" %>
      </div>

    <% end %>

app/views/products/_form2.html.erb
    <%= form_for [@product], url: product_path, html: { multipart: true } do |form| %>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, :class => "form-control", id: :product_title %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, :class => "form-control", id: :product_description %>
      </div>

      <div class="form-group">
        <%= form.label :price %>
        <%= form.number_field :price, value: number_to_currency(form.object.price.to_f, delimiter: '', unit: ''), step: :any, :class => "form-control", id: :product_price %>
      </div>

      <div class="form-group">
        <%= form.select :category, options_for_select([['Select One', ''], 'independant', 'graphic novel','merchandise']), :class => "form-control"%>
      </div>

      <div class="control-group">
        <div class="controls">
          <%= form.file_field :image, type: :file, multiple: true %>
        </div>
      </div>
      <br>

      <div class="actions">
        <%= form.submit :class => "btn btn-primary" %>
      </div>

    <% end %>

app/views/products/_product_display.html.erb
<div class="events">
  <div class="container">

    <div class="title-bar">
      <h1><%= @product.title %></h1>
    </div>
    <p id="notice"><%= notice %></p>

    <%= image_tag @product.images[0].image.url(:large) %>

      <h3>Description:</h3>
      <%= @product.description %>


      <h3>Price:</h3>
      $<%= @product.price %>
      <br><br>

      <%= form_for @order_items, remote:true  do |f| %>
        <%= f.hidden_field :product_id, value: product.id %>
        <%= f.number_field :quantity, min: '1'  %>
        <%= f.submit "Add to cart", :class => 'btn btn-primary' %>
      <% end %>
      <br><br>

      <%= link_to 'Checkout', cart_path, :class => 'btn btn-primary'  %>

      <% if is_admin? %>
        <%= link_to 'Delete Product', @product,:class => "btn btn-primary btn-lg", method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit', edit_product_path(@product),:class => "btn btn-primary btn-lg" %>
      <% end %>
    <br><br>

  </div>
</div>

app/views/products/edit.html.erb
<div class="events">
  <div class="container">
    <br><br>
    <h1>Editing Product</h1>

    <%= render 'form2', event: @product %>

    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', product_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class="events">
  <div class="container">
  <p id="notice"><%= notice %></p>
  <br><br><br>
<% if is_admin? %>
  <%= link_to 'New Product', new_product_path %>
  <% end %>
  <h1 style="text-align:center;">Products</h1>

<hr>
    <div class="container">
    	<div class="row">
        <% @products.each do |product| %>
    		<div class="col-xs-18 col-sm-4 col-md-3 col-lg-4">
    			<div class="productbox">
    				<div class="imgthumb img-responsive">
    					  <%= link_to (image_tag product.images[0].image.url(:large), :class => ('card-img-top images')), product_path(product),remote: true %>
    				</div>
    				<div class="caption">
    					<h3><%= product.title %></h3>
              <h5>$<%= product.price %></h5>
    				</div>
    			</div>
    		</div>
        <% end %>
        <div class="col-xs-18 col-sm-4 col-md-3" id="result"></div>
    	</div><!--/row-->
    </div><!--/container -->

    <br><br>
  </div>
</div>

app/views/products/new.html.erb
<div class="events">
  <br>
  <br>
  <br>
  <h1 style="text-align:center;">Add a New Product</h1>
  <div class="container">
    <h1>New Product</h1>
    <%= render 'form', event: @product %>
    <br>
    <%= link_to 'Back', products_path, :class => "btn btn-primary" %>
  </div>
  <br>
</div>

app/views/products/show.html.erb
<h1>Product Page</h1>
<br>
<hr>
<%= render 'product_display', :product=>@product %>

app/views/products/show.js.erb
$(document).ready(function(){
  $('#result').html('<div id="myModal" class="container modal fade"> <div class="modal-dialog">  <div class="modal-content">     <div class="modal-header">    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>  <h4 class="modal-title">Produt Details</h4> </div>  <div class="modal-body">  <%= j render "product_display", :product=>@product %>    </div>     </div>   </div></div> ');
  $("#myModal").modal('show');
});