config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :products
  resources :events
  resource :cart, only: [:show]
  resource :account, only: [:show]


  resources :users, only: [:index]


  resources :orders do
  resources :order_items
  end
  resources :order_items
  resources :addresses do
    resources :charges
  end


  root :to => 'welcome#index'

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to  :user

  has_many :orders
  has_many :addresses
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :account
  has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_attached_file :images, styles: { medium: "300x300>", thumb: "100x100>", large: "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :images, content_type: /\Aimage\/.*\z/

end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :product

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", large: "400x400>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  belongs_to :account
  has_one :address

  before_save :update_total
  before_create :update_status

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :account

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = current_order.total_price * 100
    @address = Address.find(params[:address_id])
  end

  def create
    # Amount in cents
    @amount = (current_order.total_price * 100).to_i
    @address = Address.find(params[:address_id])

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken],
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    current_order.update({:status => "Paid",:address_id => @address.id})
    current_user.account.update({:address_id => @address.id})
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def charges_params
    params.require(:charges).permit(:address)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :location, :date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
    @number = rand(1..15)
    @events = Event.all
    @remoteip = request.remote_ip

  end


private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :content, :location, :date, :images)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Destiny City Comics</title>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBN8m4iJ3LtZhl97zm5MjlDrOH_0RuGxE&callback=initMap">
    </script>

    <script>
     $(function() {
     $.getJSON("//extreme-ip-lookup.com/json/",
      function(json) {
       if (json.country && json.city) {
        $('#ipLookup').html('Location of '+json.query+': '+json.city+', '+json.country+'');
       }
      }
     );
     });
    </script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <nav class="navbar navbar-inverse navbar-static-top" role="navigation" id="nav">
    <div class="navbar-header navbar-right">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="collapse-1">
      <ul class="nav navbar-nav" id="nav">
        <% if is_admin? %>
        <li><%= link_to 'Admin', users_path %></li>
        <% end %>
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "Store", products_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <% if current_user %>
        <li><%= link_to 'Cart', cart_path %></li>
        <% if current_order.total_price == nil || current_order.total_price == 0.0 %>
        <li id="cart-amount"><h5 style="margin-top:17px;">Empty</h5></li>
        <% else %>
          <li id="cart-amount"><h5 style="margin-top:17px;">$<%= current_order.total_price %></h5></li>
        <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <li><%= link_to "Order history", account_path %></li>
              </ul>
            </li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :data => {:method=>'delete'} %></li>
        <% else %>
        <li><%= link_to 'Sign Up',  new_user_registration_path %></a></li>
        <li><%= link_to 'Sign In', new_user_session_path %></a></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
      <%= yield %>
  </body>

  <footer class="container">
   <div class="container">
     <div class="row">
       <div class="col-xs-18 col-sm-4 col-md-4 col-lg-4">
           <%= image_tag ('DestinyCityComicsLogo'), :class => 'logo' %>
       </div>

       <div class="col-xs-18 col-sm-4 col-md-4 col-lg-4">
         <div class="wm-1"></div>
         <h2 style="color:white; font-family:'comics'; font-size: 30px;">Store Hours</h2>
          <p style="text-align: left; color:white; font-family:'comics'; font-size: 20px;">
          Monday: CLOSED <br>
          Tuesday: 1pm to 6 pm <br>
          Wednesday: 12 noon to 8 pm <br>
          Thursday: 12 noon to 8 pm <br>
          Friday: 12 noon to 8 pm <br>
          Saturday: 12 noon to 8 pm <br>
          Sunday: 12 noon to 6 pm <br>
            </p>
       </div>

        <div class="col-xs-18 col-sm-4 col-md-4 col-lg-4">
          <div class="wm-1"></div>
          <i class="icon_mobile id-color size40 mb20"></i>
          <h2 style="color:white; font-family:'comics'; font-size: 30px;">CONTACT</h2>
          <p style="text-align: left; color:white; font-family:'comics'; font-size: 20px;">Destiny City Comics <br>
            218 Saint Helens Avenue <br>
            Tacoma, WA 98402 <br>
            Phone: (253) 234-7112 <br>
            <a href="mailto:mikefitz@destinycitycomics.com?12">Email: mikefitz@destinycitycomics.com</a> <br>
             </p>
            <%= @remoteip %>
        </div>
       </div>
     </div>
   </footer>
</html>